-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 14:47:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`redditPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`redditPost` (
  `postID` INT NOT NULL,
  `postTitle` VARCHAR(1024) NULL,
  `postLink` VARCHAR(255) NULL,
  `postDate` DATETIME NULL,
  PRIMARY KEY (`postID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`redditComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`redditComment` (
  `commentID` INT NOT NULL,
  `redditPost_postID` INT NOT NULL,
  `commentData` VARCHAR(1024) NULL,
  `CommentDate` DATETIME NULL,
  PRIMARY KEY (`commentID`, `redditPost_postID`),
  INDEX `fk_redditComment_redditPost_idx` (`redditPost_postID` ASC),
  CONSTRAINT `fk_redditComment_redditPost`
    FOREIGN KEY (`redditPost_postID`)
    REFERENCES `mydb`.`redditPost` (`postID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
